# Header
menu:
  Home: /
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
kudos: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus: UA-54151441-1
fb_admins:
fb_app_id:
